version: 2

build:
  os: windows10
  tools:
    python: "3.9.13"

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - requirements: requirements.txt
    - method: pip